import {
  HddFilled,
  InteractionFilled,
  CreditCardFilled,
  SlackCircleFilled,
  ToolFilled,
  ProjectFilled,
  FormatPainterFilled,
  GoldenFilled,
  ThunderboltFilled,
  RedditCircleFilled,
  FolderOpenFilled,
  UsbFilled,
  ExperimentFilled,
  FileAddFilled,
  RestFilled,
  TagsFilled,
  SoundFilled,
  FileTextFilled,
  ScheduleFilled,
  RobotFilled,
  FileMarkdownFilled,
  ApiFilled,
  WalletOutlined,
  ShopOutlined,
  ProfileOutlined,
  PullRequestOutlined,
  DatabaseOutlined,
  ShoppingCartOutlined,
  PoundOutlined,
  FileSearchOutlined,
  BarChartOutlined,
  AlertOutlined,
  HistoryOutlined,
  ProfileFilled,
  FileDoneOutlined,
  FileExclamationOutlined,
} from "@ant-design/icons";

export default {
  AssetsList: HddFilled,
  DestributeAndCancelStock: InteractionFilled,
  LendAndReturn: CreditCardFilled,
  InventoryManager: SlackCircleFilled,
  MaintainManager: ToolFilled,
  ScrapManager: RestFilled,
  AssetClass: ProjectFilled,
  PlaceManager: FormatPainterFilled,
  OrgManager: GoldenFilled,
  AssetTrack: ThunderboltFilled,
  EmployeeManager: RedditCircleFilled,
  AssetMonitor: FolderOpenFilled,
  TagPrint: TagsFilled,
  Reminder: SoundFilled,
  DevicePlace: UsbFilled,
  StatusMonitor: ExperimentFilled,
  UserManager: FileAddFilled,
  BillManager: FileTextFilled,
  OrgAndUser: ScheduleFilled,
  AssetJianKong: RobotFilled,
  AssetManager: FileMarkdownFilled,
  DeviceManager: ApiFilled,
  ProviderManager: WalletOutlined,
  MaterialManager: ShopOutlined,
  MaterialList: ProfileOutlined,
  MaterialOutAndReturn: PullRequestOutlined,
  MaterialEnterWarehouse: DatabaseOutlined,
  AssetPurchasedManager: ShoppingCartOutlined,
  PurchasedList: ProfileOutlined,
  PaymentList: PoundOutlined,
  PaymentHistory: FileSearchOutlined,
  Dashboard: BarChartOutlined,
  WarningList: AlertOutlined,
  AssetHistory: HistoryOutlined,
  OfflineRecord: ProfileFilled,
  DataAnalyze: FileDoneOutlined,
  AssetWarn: FileExclamationOutlined,
};
